name: conversation_v2_build

on: push

jobs:
  build_and_deploy_to_docker:
    runs-on: ubuntu-latest
    steps:
      - name: checkout_code
        uses: actions/checkout@v2

      - name: docker_login
        uses: docker/login-action@v1
        with: 
          username: ${{secrets.DOCKER_USERNAME}}
          password: ${{secrets.DOCKER_PASSWORD}}
          
      - name: docker_push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: saifullahedu0/conversation_v2:latest
        
  
